stages:
  - docker
  - tag


.build_docker_template:
  only:
    - pushes
    - merge_requests
  tags:
    - docker-privileged
  image: docker:19.03.1
  services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    
  script:
    - docker build -t ${TO} .
    - docker push ${TO}

#--------------------------------------------------------------------
build_docker_base:
  stage: docker
  extends: .build_docker_template
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}


tag_latest:
  stage: tag
  image: alpine
  only:
    refs:
      - master
  script:
    - apk add --no-cache skopeo
    - skopeo login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - skopeo copy "docker://${IMAGE_ORIGIN_TAG}" "docker://${IMAGE_DESTINATION_LATEST}"
  variables:
    IMAGE_ORIGIN_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    IMAGE_DESTINATION_LATEST: ${CI_REGISTRY_IMAGE}:latest