.build_docker_template:
  only:
    - pushes
    - merge_requests
  tags:
    - docker-privileged
  image: docker:19.03.1
  services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    
  script:
    - docker build -t ${TO} .
    - docker push ${TO}

#--------------------------------------------------------------------
build_docker_base:
  extends: .build_docker_template
  variables:
    TO: ${CI_REGISTRY_IMAGE}:latest