name: spanet_mmd
version: v1
description: 'Like v2 without mmd'
# input_dataset: /eos/user/d/dvalsecc/www/ttHbbAnalysis/training_dataset/v3_sig_forTrainingDataset/all_jets_fullRun2_ttHbb_forTraining_allyears_spanetprov_part1
input_dataset: /work/dvalsecc/MEM/datasets/all_jets_fullRun2_ttHbb_forTraining_allyears_spanetprov_part1
cartesian: false
noProv: true
input_shape:
  number_jets: 16
  number_lept: 1
  input_features: 7  # now with 3 prov probabilities
scaling_params:
  log_mean: [4.6710e+00, 2.8028e-05, 7.9478e-04]
  log_std: [0.9195, 1.2910, 1.8139]
training_params:
  lr: 0.0001
  batch_size_training: 256
  batch_size_validation: 512
  subsplit: 8
  nepochs: 1000
  training_sample: 0.9
  validation_sample: 0.1
  sampling_points_loss: 150
  percentage_sampling_epoch: 0.2
  sampling_points: 100
  nEpochsPatience: 50
  eps: 1.0e-05
  mmd_kernel: "multiscale"
  order:
  - 0
  - 1
  - 2
  - 3
  sampling_Forward: false
conditioning_transformer:
  out_features: 3
  hidden_features: 64
  dim_feedforward_transformer: 1024
  nhead_encoder: 4
  no_layers_encoder: 6
  nhead_decoder: 4
  no_layers_decoder: 4
  aggregate: false
  no_decoders: 3
  use_latent: true
  no_layers_decoder_latent: 4
  out_features_latent: 8
unfolding_flow:
  nfeatures: 10
  ncond: 32
  ntransforms: 10
  hiddenMLP_NoLayers: 4
  hiddenMLP_LayerDim: 128
  bins: 35
  autoregressive: false
  base: DiagNormal
  base_first_arg: 0
  base_second_arg: 0.3
  bound: 1.5
MDMM:
  max_huber: 0.1
  scale_huber : 1
  dumping_huber: 1.
